---
- name: IOS Config Demo
  hosts: routers_ssh_pass

  tasks:
    - name: Interface Configuration
      ios_interfaces:
        config:
          - name: GigabitEthernet0/1
            description: Ansible Configured
            enabled: yes
            duplex: full
            speed: 1000
        state: merged
      register: int

    - debug:
        var: int.before
    - debug:
        var: int.commands
    - debug:
        var: int.after

#################### Delete ##############
    - name: Interface Configuration
      ios_interfaces:
        config:
          - name: GigabitEthernet0/1
        state: deleted
      register: int
    - debug:
        var: int.commands

#################### Overridden ##############
    - name: Interface Configuration
      ios_interfaces:
        config:
          - name: GigabitEthernet0/1
            enabled: yes
        state: overridden

############# Replaced ###############
    - name: Interface Configuration
      ios_interfaces:
        config:
          - name: GigabitEthernet0/1
            description: Ansible Configured
            enabled: yes
            duplex: full
            speed: 1000
        state: replaced
      register: int
    - debug:
        var: int.before
    - debug:
        var: int.commands
    - debug:
        var: int.after
